### ISSUE TITLE
Data for line chart does not match Safari's format 

### ISSUE THREAD

**Issue by kanitw** [gramener/visual-vocabulary-vega#1]
Here is how it looks like in Safari

<img width="825" alt="image" src="https://user-images.githubusercontent.com/111269/53618352-d1f76100-3b9f-11e9-9fde-3022de6264ab.png">

This is probably due to the fact that Safari (and perhaps Firefox) implement `Date.parse` differently from Chrome.  (See https://github.com/vega/vega-lite/issues/1389)

**Comment by pratapvardhan** [comment]
fixed via 70281f1
